# Generated by Django 4.2.1 on 2023-07-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='promocode',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
